language: php

php:
   - 7.1
   - 7.2
   - 7.3

install:
  - composer require satooshi/php-coveralls:~0.6@stable

before_script:
   - mkdir -p build/logs
   - composer install --no-interaction --dev

script:
   - vendor/bin/phpunit -c phpunit.xml.dist --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v
